CREATE DATABASE GPG;

USE GPG;

CREATE TABLE usuarios(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    name VARCHAR(255),
    rol BOOLEAN DEFAULT(0)-- 1=PROFESOR 0= ESTUDIANTE
);

CREATE TABLE calificaciones(
    id INT AUTO_INCREMENT PRIMARY KEY,
    
)

